"""Inicial

Revision ID: b32296df0240
Revises: 00ddd39d1525
Create Date: 2025-11-19 23:34:57.441908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32296df0240'
down_revision: Union[str, Sequence[str], None] = '00ddd39d1525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estaciones',
    sa.Column('estacion_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lon', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('estacion_id')
    )
    op.create_table('mibisivalencia',
    sa.Column('targeta_id', sa.String(length=9), nullable=False),
    sa.PrimaryKeyConstraint('targeta_id')
    )
    op.create_table('roles',
    sa.Column('rol_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('rol_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('bicicletas',
    sa.Column('bicicleta_id', sa.String(length=36), nullable=False),
    sa.Column('estacion_id', sa.Integer(), nullable=True),
    sa.Column('qr_code', sa.String(length=100), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.Enum('en_uso', 'estacionada', 'fuera_servicio', 'mantenimiento', name='estadobicicleta'), nullable=False),
    sa.ForeignKeyConstraint(['estacion_id'], ['estaciones.estacion_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('bicicleta_id'),
    sa.UniqueConstraint('qr_code'),
    sa.UniqueConstraint('short_code')
    )
    op.create_table('pending_registrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('targeta_id', sa.String(length=9), nullable=True),
    sa.Column('contrasena_hash', sa.Text(), nullable=False),
    sa.Column('verification_code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['targeta_id'], ['mibisivalencia.targeta_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('usuarios',
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('targeta_id', sa.String(length=9), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('contrasena_hash', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['targeta_id'], ['mibisivalencia.targeta_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('incidencias',
    sa.Column('incidencia_id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.Column('bicicleta_id', sa.String(length=36), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_reporte', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('estado', sa.Enum('nuevo', 'en_proceso', 'resuelto', 'cerrado', name='estadoincidencia'), nullable=True),
    sa.Column('fuente', sa.Enum('app', 'web', 'admin', name='fuentereporte'), nullable=False),
    sa.ForeignKeyConstraint(['bicicleta_id'], ['bicicletas.bicicleta_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('incidencia_id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('placas_sensores',
    sa.Column('placa_id', sa.String(length=36), nullable=False),
    sa.Column('bicicleta_id', sa.String(length=36), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['bicicleta_id'], ['bicicletas.bicicleta_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('placa_id'),
    sa.UniqueConstraint('bicicleta_id')
    )
    op.create_table('trayectos',
    sa.Column('trayecto_id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.Column('bicicleta_id', sa.String(length=36), nullable=True),
    sa.Column('fecha_inicio', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('origen_estacion_id', sa.Integer(), nullable=True),
    sa.Column('destino_estacion_id', sa.Integer(), nullable=True),
    sa.Column('distancia_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bicicleta_id'], ['bicicletas.bicicleta_id'], ),
    sa.ForeignKeyConstraint(['destino_estacion_id'], ['estaciones.estacion_id'], ),
    sa.ForeignKeyConstraint(['origen_estacion_id'], ['estaciones.estacion_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('trayecto_id')
    )
    op.create_table('usuario_roles',
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.rol_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id')
    )
    op.create_table('medidas',
    sa.Column('lectura_id', sa.String(length=36), nullable=False),
    sa.Column('placa_id', sa.String(length=36), nullable=True),
    sa.Column('trayecto_id', sa.String(length=36), nullable=True),
    sa.Column('fecha_hora', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('tipo', sa.Enum('pm2_5', 'pm10', 'co', 'no2', 'o3', 'temperatura', 'humedad', name='tipomedidaenum'), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lon', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['placa_id'], ['placas_sensores.placa_id'], ),
    sa.ForeignKeyConstraint(['trayecto_id'], ['trayectos.trayecto_id'], ),
    sa.PrimaryKeyConstraint('lectura_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medidas')
    op.drop_table('usuario_roles')
    op.drop_table('trayectos')
    op.drop_table('placas_sensores')
    op.drop_table('password_reset_tokens')
    op.drop_table('incidencias')
    op.drop_table('usuarios')
    op.drop_table('pending_registrations')
    op.drop_table('bicicletas')
    op.drop_table('roles')
    op.drop_table('mibisivalencia')
    op.drop_table('estaciones')
    # ### end Alembic commands ###
