# Autor: Denys Litvynov
# Fecha : 08/12/2025
# Descripción : Dockerfile para el frontend.

# Usamos Nginx alpine para ligereza
FROM nginx:alpine

# Copiamos solo el frontend estático (sin tests ni extras)
COPY frontend/ /usr/share/nginx/html/

# Copiamos configuración personalizada de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exponemos puerto 80
EXPOSE 80
